# CI pipeline runs on PRs and for every commit on main
# Runs: rustfmt, Clippy, build, test, doctest, doc build
name: Rust

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      # Install nightly toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt

      # Install stable toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          default: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Format check
        run: cargo +nightly fmt --all -- --check

      - name: Clippy lint
        run: cargo clippy --all-features --all-targets --verbose --workspace -- -Dwarnings

      - name: Build
        run: cargo build --all-features --all-targets --verbose --workspace

      - name: Run all unit + library tests (not doc, integration, benchmark, or example tests)
        run: cargo test --all-features --bins --workspace

      - name: Build documentation
        run: RUSTDOCFLAGS="-Dwarnings" cargo doc --all-features --no-deps --verbose --workspace
